# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false
matrix:
  include:
    - python: 3.5
before_install:
  - travis_retry pip install Sphinx matplotlib
script:
  - make -C www html
  # Deploy built docs, see:
  # https://developer.github.com/guides/managing-deploy-keys/
  # http://docs.travis-ci.com/user/encrypting-files/
  - |
    if [ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_BRANCH}" == "master" ]; then
        set -e
        openssl aes-256-cbc -K $encrypted_b20b752c8ad0_key -iv $encrypted_b20b752c8ad0_iv -in .ci/deploy-key.enc -out .ci/deploy-key -d
        chmod 600 .ci/deploy-key
        eval `ssh-agent -s`
        ssh-add .ci/deploy-key < /dev/null
        git config --global user.email "scipy-travis-bot@nomail"
        git config --global user.name "scipy-travis-bot"
        git config --global push.default simple
        make -C www deploy
    fi
